using System;
namespace Px.Net.Common.Models
{
	/// <summary>
	/// Structured response object for Mediator/CQRS commands and queries.
	/// </summary>
	public class MediatorResult
	{
		private readonly bool _succeeded;
		private readonly object? _data;

		private readonly Exception? _exception;
		private readonly string? _errorMessage;

		/// <summary>
		/// Indicates whether the command/query executed succesfully
		/// </summary>
		public bool Succeeded =>
			_succeeded;

		/// <summary>
		/// Possible response object of the command/query execution
		/// </summary>
		public object? Data =>
			_data;

		/// <summary>
		/// In case of an error, this property contains the error message generated by the command/query execution.
		/// </summary>
		public string ErrorMessage =>
			_exception?.Message ?? _errorMessage ?? "?";

		private MediatorResult(bool succeeded, object? data = null, Exception? exception = null, string? errorMessage = null)
		{
			_succeeded = succeeded;
			_data = data;
			_exception = exception;
			_errorMessage = errorMessage;
		}

		/// <summary>
		/// Create a failed execution response
		/// </summary>
		/// <param name="exception">The exception that occurred</param>
		/// <returns></returns>
		public static MediatorResult HasFailed(Exception exception) =>
			new(false, exception: exception, errorMessage: exception.Message);

		/// <summary>
		/// Create a failed execution response
		/// </summary>
		/// <param name="errorMessage">The descriptive error message for the failure.</param>
		/// <returns></returns>
		public static MediatorResult HasFailed(string errorMessage) =>
			new(false, errorMessage: errorMessage);

		/// <summary>
		/// Create a succesfull execution response
		/// </summary>
		/// <param name="data">The optional data object that should be returned</param>
		/// <returns></returns>
		public static MediatorResult HasSucceeded(object? data = null)
			=> new(true, data);
	}
}

